package rosa.archive.core;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Tests for {@link ImageListDecorator}.
 */
class ImageListDecoratorTest {

    @TempDir
    Path tempDir;

    private Path archiveDir;
    private Path bookDir;
    private static final String COLLECTION = "testcol";
    private static final String BOOK = "testbook";

    @BeforeEach
    void setUp() throws IOException {
        archiveDir = tempDir;
        bookDir = archiveDir.resolve(COLLECTION).resolve(BOOK);
        Files.createDirectories(bookDir);
    }

    @Test
    void decorateBook_prefersPagenationOverSignature() throws IOException {
        // Image list with two images
        String imagesCsv = "testbook.aor.001r.tif,1000,1500,false\ntestbook.aor.002r.tif,1000,1500,false\n";
        Files.writeString(bookDir.resolve(BOOK + ".images.csv"), imagesCsv);

        // AoR transcription with both pagination and signature
        writeTranscription("testbook.aor.001r.xml",
                "testbook.aor.001r.tif", "42r", "A1r");

        // AoR transcription with only signature
        writeTranscription("testbook.aor.002r.xml",
                "testbook.aor.002r.tif", null, "B2v");

        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateBook(COLLECTION, BOOK, errors);

        assertTrue(errors.isEmpty(), "Expected no errors but got: " + errors);

        List<String> lines = Files.readAllLines(bookDir.resolve(BOOK + ".images.csv"));
        assertEquals(2, lines.size());

        // First: pagination preferred over signature
        String[] parts1 = lines.get(0).split(",");
        assertEquals("testbook.aor.001r.tif", parts1[0]);
        assertEquals("42r", parts1[4]);
        assertEquals("false", parts1[5]);

        // Second: signature used as fallback
        String[] parts2 = lines.get(1).split(",");
        assertEquals("testbook.aor.002r.tif", parts2[0]);
        assertEquals("B2v", parts2[4]);
        assertEquals("false", parts2[5]);
    }

    @Test
    void decorateBook_marksAutoGeneratedWhenNoTranscription() throws IOException {
        // Image list with three images, only one has a transcription
        String imagesCsv = "testbook.aor.001r.tif,1000,1500,false\n"
                + "testbook.aor.002r.tif,1000,1500,false\n"
                + "testbook.aor.003r.tif,1000,1500,false\n";
        Files.writeString(bookDir.resolve(BOOK + ".images.csv"), imagesCsv);

        // Only one transcription file
        writeTranscription("testbook.aor.001r.xml",
                "testbook.aor.001r.tif", "1r", null);

        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateBook(COLLECTION, BOOK, errors);

        assertTrue(errors.isEmpty(), "Expected no errors but got: " + errors);

        List<String> lines = Files.readAllLines(bookDir.resolve(BOOK + ".images.csv"));
        assertEquals(3, lines.size());

        // First: has transcription, not auto-generated
        String[] parts1 = lines.get(0).split(",");
        assertEquals("1r", parts1[4]);
        assertEquals("false", parts1[5]);

        // Second: no transcription, auto-generated
        String[] parts2 = lines.get(1).split(",");
        assertEquals("", parts2[4]);
        assertEquals("true", parts2[5]);

        // Third: no transcription, auto-generated
        String[] parts3 = lines.get(2).split(",");
        assertEquals("", parts3[4]);
        assertEquals("true", parts3[5]);
    }

    @Test
    void decorateBook_reportsErrorWhenImageListMissing() {
        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateBook(COLLECTION, BOOK, errors);

        assertEquals(1, errors.size());
        assertTrue(errors.get(0).contains("Image list not found"));
    }

    @Test
    void decorateBook_reportsErrorWhenBookNotFound() {
        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateBook(COLLECTION, "nonexistent", errors);

        assertEquals(1, errors.size());
        assertTrue(errors.get(0).contains("Book directory not found"));
    }

    @Test
    void decorateCollection_processesAllBooks() throws IOException {
        // Use a separate collection for this test to avoid interference from setUp's testbook
        String colId = "multicol";
        Path book1Dir = archiveDir.resolve(colId).resolve("book1");
        Path book2Dir = archiveDir.resolve(colId).resolve("book2");
        Files.createDirectories(book1Dir);
        Files.createDirectories(book2Dir);

        Files.writeString(book1Dir.resolve("book1.images.csv"),
                "book1.aor.001r.tif,100,200,false\n");
        writeTranscriptionAt(book1Dir, "book1.aor.001r.xml",
                "book1.aor.001r.tif", "10r", null);

        Files.writeString(book2Dir.resolve("book2.images.csv"),
                "book2.aor.001v.tif,100,200,false\n");
        writeTranscriptionAt(book2Dir, "book2.aor.001v.xml",
                "book2.aor.001v.tif", null, "C3");

        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateCollection(colId, errors);

        assertTrue(errors.isEmpty(), "Expected no errors but got: " + errors);

        // Verify book1 was decorated
        List<String> book1Lines = Files.readAllLines(book1Dir.resolve("book1.images.csv"));
        assertEquals(1, book1Lines.size());
        assertTrue(book1Lines.get(0).contains("10r"));
        assertTrue(book1Lines.get(0).endsWith("false"));

        // Verify book2 was decorated
        List<String> book2Lines = Files.readAllLines(book2Dir.resolve("book2.images.csv"));
        assertEquals(1, book2Lines.size());
        assertTrue(book2Lines.get(0).contains("C3"));
        assertTrue(book2Lines.get(0).endsWith("false"));
    }

    @Test
    void decorateBook_handlesTranscriptionWithNeitherPaginationNorSignature() throws IOException {
        String imagesCsv = "testbook.aor.001r.tif,1000,1500,false\n";
        Files.writeString(bookDir.resolve(BOOK + ".images.csv"), imagesCsv);

        // Transcription with neither pagination nor signature
        writeTranscription("testbook.aor.001r.xml",
                "testbook.aor.001r.tif", null, null);

        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateBook(COLLECTION, BOOK, errors);

        assertTrue(errors.isEmpty(), "Expected no errors but got: " + errors);

        List<String> lines = Files.readAllLines(bookDir.resolve(BOOK + ".images.csv"));
        assertEquals(1, lines.size());
        String[] parts = lines.get(0).split(",");
        assertEquals("", parts[4]);
        assertEquals("true", parts[5]);
    }

    @Test
    void decorateCollection_reportsErrorWhenCollectionNotFound() {
        var decorator = new ImageListDecorator(archiveDir);
        List<String> errors = new ArrayList<>();
        decorator.decorateCollection("nonexistent", errors);

        assertEquals(1, errors.size());
        assertTrue(errors.get(0).contains("Collection directory not found"));
    }

    private void writeTranscription(String filename, String pageFilename,
                                    String pagination, String signature) throws IOException {
        writeTranscriptionAt(bookDir, filename, pageFilename, pagination, signature);
    }

    private void writeTranscriptionAt(Path dir, String filename, String pageFilename,
                                      String pagination, String signature) throws IOException {
        var sb = new StringBuilder();
        sb.append("<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"no\"?>\n");
        sb.append("<transcription>\n");
        sb.append("    <page filename=\"").append(pageFilename).append("\" reader=\"Harvey\"");
        if (pagination != null) {
            sb.append(" pagination=\"").append(pagination).append("\"");
        }
        if (signature != null) {
            sb.append(" signature=\"").append(signature).append("\"");
        }
        sb.append("/>\n");
        sb.append("    <annotation>\n");
        sb.append("    </annotation>\n");
        sb.append("</transcription>\n");
        Files.writeString(dir.resolve(filename), sb.toString(), StandardCharsets.UTF_8);
    }
}
