language: java

sudo: false
dist: trusty

cache:
    directories:
      - $HOME/.m2

before_script:
  - git clone https://github.com/jhu-digital-manuscripts/lucene-latin-stemmer
  - cd lucene-latin-stemmer && mvn install && cd -

script:
  - mvn test
