package rosa.archive.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * A high resolution image of a page in a book. Dimensions should be in pixels!
 */
public class BookImage implements Serializable {
    private static final long serialVersionUID = 1L;

    private String id;
    private int width;
    private int height;
    private boolean isMissing;

    private String name;
    private boolean autoGeneratedName;
    private BookImageLocation location;
    private BookImageRole role;
//    private char side; TODO if needed

    /**
     * Create an empty BookImage
     */
    public BookImage() {
        this(null, -1, -1, true);
    }

    /**
     * Create a BookImage with parameters.
     *
     * @param id ID
     * @param width width in pixels
     * @param height height in pixels
     * @param isMissing is this image missing from the archive?
     */
    public BookImage(String id, int width, int height, boolean isMissing) {
        this.id = id;
        this.width = width;
        this.height = height;
        this.isMissing = isMissing;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public BookImageLocation getLocation() {
        return location;
    }

    public void setLocation(BookImageLocation location) {
        this.location = location;
    }

    public BookImageRole getRole() {
        return role;
    }

    public void setRole(BookImageRole role) {
        this.role = role;
    }

    public int getWidth() {
        return width;
    }

    public void setWidth(int width) {
        this.width = width;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public boolean isMissing() {
        return isMissing;
    }

    public void setMissing(boolean isMissing) {
        this.isMissing = isMissing;
    }

    public boolean isAutoGeneratedName() {
        return autoGeneratedName;
    }

    public void setAutoGeneratedName(boolean autoGeneratedName) {
        this.autoGeneratedName = autoGeneratedName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        BookImage bookImage = (BookImage) o;
        return width == bookImage.width &&
                height == bookImage.height &&
                isMissing == bookImage.isMissing &&
                autoGeneratedName == bookImage.autoGeneratedName &&
                Objects.equals(id, bookImage.id) &&
                Objects.equals(name, bookImage.name) &&
                location == bookImage.location &&
                role == bookImage.role;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, width, height, isMissing, name, autoGeneratedName, location, role);
    }

    @Override
    public String toString() {
        return "BookImage{" +
                "id='" + id + '\'' +
                ", width=" + width +
                ", height=" + height +
                ", isMissing=" + isMissing +
                ", name='" + name + '\'' +
                ", autoGeneratedName=" + autoGeneratedName +
                ", location=" + location +
                ", role=" + role +
                '}';
    }
}
