package rosa.archive.model;

import java.util.Objects;

/**
 * A high-resolution image of a page in a book. Dimensions are in pixels.
 */
public class BookImage {

    private String id;
    private int width;
    private int height;
    private boolean missing;
    private String name;
    private boolean autoGeneratedName;
    private BookImageLocation location;
    private BookImageRole role;

    /**
     * Creates an empty BookImage with default values (no id, dimensions of -1, marked as missing).
     */
    public BookImage() {
        this(null, -1, -1, true);
    }

    /**
     * Creates a BookImage with the specified parameters.
     *
     * @param id        the image identifier
     * @param width     the image width in pixels
     * @param height    the image height in pixels
     * @param missing   whether this image is missing from the archive
     */
    public BookImage(String id, int width, int height, boolean missing) {
        this.id = id;
        this.width = width;
        this.height = height;
        this.missing = missing;
    }

    /**
     * Returns the image identifier.
     *
     * @return the image id
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the image identifier.
     *
     * @param id the image id
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Returns the short display name for this image.
     *
     * @return the image name, or {@code null} if not set
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the short display name for this image.
     *
     * @param name the image name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the physical location of this image within the book.
     *
     * @return the image location
     */
    public BookImageLocation getLocation() {
        return location;
    }

    /**
     * Sets the physical location of this image within the book.
     *
     * @param location the image location
     */
    public void setLocation(BookImageLocation location) {
        this.location = location;
    }

    /**
     * Returns the role of this image within the book structure.
     *
     * @return the image role
     */
    public BookImageRole getRole() {
        return role;
    }

    /**
     * Sets the role of this image within the book structure.
     *
     * @param role the image role
     */
    public void setRole(BookImageRole role) {
        this.role = role;
    }

    /**
     * Returns the image width in pixels.
     *
     * @return the width
     */
    public int getWidth() {
        return width;
    }

    /**
     * Sets the image width in pixels.
     *
     * @param width the width
     */
    public void setWidth(int width) {
        this.width = width;
    }

    /**
     * Returns the image height in pixels.
     *
     * @return the height
     */
    public int getHeight() {
        return height;
    }

    /**
     * Sets the image height in pixels.
     *
     * @param height the height
     */
    public void setHeight(int height) {
        this.height = height;
    }

    /**
     * Returns whether this image is missing from the archive.
     *
     * @return {@code true} if the image is missing
     */
    public boolean isMissing() {
        return missing;
    }

    /**
     * Sets whether this image is missing from the archive.
     *
     * @param missing {@code true} if the image is missing
     */
    public void setMissing(boolean missing) {
        this.missing = missing;
    }

    /**
     * Returns whether the name of this image was auto-generated rather than explicitly assigned.
     *
     * @return {@code true} if the name was auto-generated
     */
    public boolean isAutoGeneratedName() {
        return autoGeneratedName;
    }

    /**
     * Sets whether the name of this image was auto-generated.
     *
     * @param autoGeneratedName {@code true} if auto-generated
     */
    public void setAutoGeneratedName(boolean autoGeneratedName) {
        this.autoGeneratedName = autoGeneratedName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BookImage that)) return false;
        return width == that.width &&
                height == that.height &&
                missing == that.missing &&
                autoGeneratedName == that.autoGeneratedName &&
                Objects.equals(id, that.id) &&
                Objects.equals(name, that.name) &&
                location == that.location &&
                role == that.role;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, width, height, missing, name, autoGeneratedName, location, role);
    }

    @Override
    public String toString() {
        return "BookImage{" +
                "id='" + id + '\'' +
                ", width=" + width +
                ", height=" + height +
                ", missing=" + missing +
                ", name='" + name + '\'' +
                ", autoGeneratedName=" + autoGeneratedName +
                ", location=" + location +
                ", role=" + role +
                '}';
    }
}
