version: '2'

services:

  opensearch:
    image: opensearchproject/opensearch:2
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - DISABLE_SECURITY_PLUGIN=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - osdata:/usr/share/opensearch/data
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:Z
      - ../opensearch/latin-stemmer-rules.txt:/usr/share/opensearch/config/analyzers/latin-stemmer-rules.txt:Z
      - ../opensearch/latin-charmap.txt:/usr/share/opensearch/config/analyzers/latin-charmap.txt:Z
    ports:
      - "9200:9200"

volumes:
  osdata:
    driver: local
