package rosa.archive.core;

import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;
import org.xml.sax.SAXException;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Decorates a book's image list CSV with page labels extracted from AoR transcription files.
 *
 * <p>For each book, this utility reads the existing {@code <bookId>.images.csv}, marks all
 * entries as auto-generated initially, then reads each AoR transcription XML to extract
 * pagination and signature attributes from the {@code <page>} element. The pagination
 * attribute is preferred over signature when both are present. The resulting label is
 * written back into the image list CSV.</p>
 *
 * <p>The decorated image list format is:
 * {@code filename,width,height,missing,label,auto_generated} (6 columns, no header row).</p>
 */
public final class ImageListDecorator {

    private static final ArchiveNameParser NAME_PARSER = new ArchiveNameParser();
    private static final String IMAGES_SUFFIX = ".images.csv";

    private final Path archivePath;

    /**
     * Creates an ImageListDecorator rooted at the given archive path.
     *
     * @param archivePath the root directory of the archive
     */
    public ImageListDecorator(Path archivePath) {
        this.archivePath = archivePath;
    }

    /**
     * Decorates image lists for all books in a collection.
     *
     * @param collectionId the collection identifier
     * @param errors       list to collect error messages
     */
    public void decorateCollection(String collectionId, List<String> errors) {
        Path collectionDir = archivePath.resolve(collectionId);
        if (!Files.isDirectory(collectionDir)) {
            errors.add("Collection directory not found: " + collectionId);
            return;
        }

        List<String> books = listBookDirectories(collectionDir, errors);
        for (String bookId : books) {
            decorateBook(collectionId, bookId, errors);
        }
    }

    /**
     * Decorates the image list for a single book by reading page labels from
     * AoR transcription XML files.
     *
     * <p>The method loads the existing image list CSV, marks all images as auto-generated,
     * then reads each transcription file to extract labels. Pagination is preferred over
     * signature when both are present on a page element.</p>
     *
     * @param collectionId the collection identifier
     * @param bookId       the book identifier
     * @param errors       list to collect error messages
     */
    public void decorateBook(String collectionId, String bookId, List<String> errors) {
        Path bookDir = archivePath.resolve(collectionId).resolve(bookId);
        if (!Files.isDirectory(bookDir)) {
            errors.add("Book directory not found: " + collectionId + "/" + bookId);
            return;
        }

        Path imagesCsv = bookDir.resolve(bookId + IMAGES_SUFFIX);
        if (!Files.isRegularFile(imagesCsv)) {
            errors.add("Image list not found: " + imagesCsv.getFileName());
            return;
        }

        // Load the image list entries
        List<ImageEntry> entries = loadImageList(imagesCsv, errors);
        if (entries.isEmpty()) {
            return;
        }

        // Build a lookup map by filename for fast matching
        Map<String, ImageEntry> entryByFilename = new LinkedHashMap<>();
        for (ImageEntry entry : entries) {
            entryByFilename.put(entry.filename, entry);
        }

        // Mark all as auto-generated initially
        for (ImageEntry entry : entries) {
            entry.label = "";
            entry.autoGenerated = true;
        }

        // Read AoR transcription XML files and extract page labels
        List<String> transcriptions = listAorTranscriptions(bookDir, errors);
        for (String transcriptionFile : transcriptions) {
            processTranscription(bookDir, transcriptionFile, entryByFilename, errors);
        }

        // Write back the decorated image list
        writeImageList(imagesCsv, entries, errors);
    }

    private void processTranscription(Path bookDir, String transcriptionFile,
                                      Map<String, ImageEntry> entryByFilename, List<String> errors) {
        Path filePath = bookDir.resolve(transcriptionFile);

        Document doc;
        try {
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            factory.setNamespaceAware(false);
            factory.setFeature("http://apache.org/xml/features/nonvalidating/load-external-dtd", false);
            DocumentBuilder builder = factory.newDocumentBuilder();
            try (InputStream in = Files.newInputStream(filePath)) {
                doc = builder.parse(in);
            }
        } catch (ParserConfigurationException | SAXException | IOException e) {
            errors.add("Failed to parse transcription [" + transcriptionFile + "]: " + e.getMessage());
            return;
        }

        // Extract page element attributes
        NodeList pageEls = doc.getElementsByTagName("page");
        if (pageEls.getLength() == 0) {
            return;
        }

        Element pageEl = (Element) pageEls.item(0);
        String filename = pageEl.getAttribute("filename");
        String pagination = pageEl.getAttribute("pagination");
        String signature = pageEl.getAttribute("signature");

        if (filename == null || filename.isBlank()) {
            return;
        }

        // Determine the label: prefer pagination over signature
        String label = "";
        if (hasContent(pagination)) {
            label = pagination;
        } else if (hasContent(signature)) {
            label = signature;
        }

        // Find the matching image entry and update it
        ImageEntry entry = entryByFilename.get(filename);
        if (entry != null && !label.isEmpty()) {
            entry.label = label;
            entry.autoGenerated = false;
        }
    }

    private List<ImageEntry> loadImageList(Path imagesCsv, List<String> errors) {
        List<ImageEntry> entries = new ArrayList<>();
        try {
            List<String> lines = Files.readAllLines(imagesCsv, StandardCharsets.UTF_8);
            for (String line : lines) {
                if (line.isBlank()) {
                    continue;
                }
                String[] parts = line.split(",", -1);
                if (parts.length >= 4) {
                    var entry = new ImageEntry();
                    entry.filename = parts[0].trim();
                    entry.width = parts[1].trim();
                    entry.height = parts[2].trim();
                    entry.missing = parts[3].trim();
                    // If previously decorated, pick up existing label/auto fields
                    if (parts.length >= 6) {
                        entry.label = parts[4].trim();
                        entry.autoGenerated = Boolean.parseBoolean(parts[5].trim());
                    } else {
                        entry.label = "";
                        entry.autoGenerated = true;
                    }
                    entries.add(entry);
                } else {
                    errors.add("Malformed image list line: " + line);
                }
            }
        } catch (IOException e) {
            errors.add("Failed to read image list: " + e.getMessage());
        }
        return entries;
    }

    private void writeImageList(Path imagesCsv, List<ImageEntry> entries, List<String> errors) {
        var sb = new StringBuilder();
        for (ImageEntry entry : entries) {
            sb.append(entry.filename).append(',');
            sb.append(entry.width).append(',');
            sb.append(entry.height).append(',');
            sb.append(entry.missing).append(',');
            sb.append(entry.label).append(',');
            sb.append(entry.autoGenerated);
            sb.append('\n');
        }
        try {
            Files.writeString(imagesCsv, sb.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            errors.add("Failed to write image list: " + e.getMessage());
        }
    }

    private List<String> listAorTranscriptions(Path bookDir, List<String> errors) {
        List<String> transcriptions = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(bookDir, Files::isRegularFile)) {
            for (Path entry : stream) {
                String name = entry.getFileName().toString();
                if (NAME_PARSER.isAorTranscription(name)) {
                    transcriptions.add(name);
                }
            }
        } catch (IOException e) {
            errors.add("Failed to list transcription files in [" + bookDir.getFileName() + "]: " + e.getMessage());
        }
        transcriptions.sort(String::compareTo);
        return transcriptions;
    }

    private List<String> listBookDirectories(Path collectionDir, List<String> errors) {
        List<String> books = new ArrayList<>();
        try (DirectoryStream<Path> stream = Files.newDirectoryStream(collectionDir, Files::isDirectory)) {
            for (Path entry : stream) {
                String name = entry.getFileName().toString();
                if (!name.startsWith(".")) {
                    books.add(name);
                }
            }
        } catch (IOException e) {
            errors.add("Failed to list books in collection: " + e.getMessage());
        }
        books.sort(String::compareTo);
        return books;
    }

    private boolean hasContent(String str) {
        return str != null && !str.isEmpty();
    }

    /**
     * Mutable holder for an image list entry during decoration processing.
     */
    private static final class ImageEntry {
        String filename = "";
        String width = "0";
        String height = "0";
        String missing = "false";
        String label = "";
        boolean autoGenerated = true;
    }
}
